version: "3.8"

services:
  tcmongodb:
    image: 'mongo' #'mongo:bionic' for rpi.
    container_name: 'tcmongodb'
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: mongogo

    volumes:
      - ./mongo-init.sh:/docker-entrypoint-initdb.d/mongo-init.sh:ro
      - mongo-volume:/data/db
    ports:
      - 27017:27017

  trashcanmon:
    image: trashcanmon:latest
    container_name: "trashcanmon"
    restart: always
    environment:
      config_path: "/code/config/config.json"
    volumes:
      - logs:/logs
      - ./config.json:/code/config/config.json:ro

volumes:
  logs:
  mongo-volume: